[workspace]
authors = ["hyzhou"]
channels = ["conda-forge"]
name = "hugsim-runtime"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-apex = { cmd = "python setup.py install --cuda_ext --cpp_ext", cwd = "external/apex" }

[dependencies]
python = "==3.11.10"
setuptools = "==78.1.0"
pip = ">=26.1.1,<27"
ninja = ">=1.11.1.4, <2"

[pypi-options]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"
no-build-isolation = ["gsplat", "pytorch3d", "tinycudann", "simple-knn", "xformers"]

[pypi-options.dependency-overrides]
xformers = { path = "./external/xformers" }

[pypi-dependencies]
torch = { path = "torch_whl/torch-2.4.1+cu118-cp311-cp311-linux_x86_64.whl" }
torchvision = { path = "torch_whl/torchvision-0.19.1+cu118-cp311-cp311-linux_x86_64.whl" }
torchmetrics = ">=1.7.1, <2"
roma = ">=1.5.2.1, <2"
matplotlib = ">=3.10.1, <4"
tqdm = ">=4.67.1, <5"
opencv-python = ">=4.11.0.86, <5"
scipy = ">=1.15.2, <2"
einops = ">=0.8.1, <0.9"
trimesh = ">=4.6.6, <5"
tensorboard = ">=2.19.0, <3"
gpustat = ">=1.1.1, <2"
scikit-learn = ">=1.6.1, <2"
open3d = ">=0.18.0, <0.19"
timm = ">=1.0.15, <2"
geometry = ">=0.0.23, <0.0.24"
gymnasium = "==1.1.1"
imageio = ">=2.37.0, <3"
jaxtyping = ">=0.3.1, <0.4"
mediapy = ">=1.2.3, <2"
omegaconf = ">=2.3.0, <3"
pillow = ">=11.2.1, <12"
plyfile = ">=1.1, <2"
pyquaternion = ">=0.9.9, <0.10"
pyyaml = ">=6.0.2, <7"
shapely = ">=2.1.0, <3"
tabulate = ">=0.9.0, <0.10"
protobuf = "==3.20.2"
runx = "==0.0.6"
fire = ">=0.7.0, <0.8"
h5py = ">=3.13.0, <4"
nose = ">=1.3.7, <2"
dominate = ">=2.9.1, <3"
cffi = ">=1.17.1, <2"
piexif = ">=1.1.3, <2"
jupyter = ">=1.1.1, <2"
ipdb = ">=0.13.13, <0.14"
numpy = ">=1.24.3, <2"
torch-fidelity = ">=0.3.0, <0.4"
huggingface-hub = ">=0.32.0, <0.33"
moviepy = ">=2.2.1, <3"

# Install third-party source packages from local submodules.
simple-knn = { path = "./external/simple-knn", editable = false }
gsplat = { path = "./external/HUGSIM_splat", editable = false }
flow-vis-torch = { path = "./external/Optical-Flow-Visualization-PyTorch", editable = false }
unidepth = { path = "./external/UniDepth", editable = false }
trajdata = { path = "./external/trajdata", editable = false }
tinycudann = { path = "./external/tiny-cuda-nn/bindings/torch", editable = false }
kitti360Scripts = { path = "./external/kitti360Scripts", editable = false }
simple-waymo-open-dataset-reader = { path = "./external/simple-waymo-open-dataset-reader", editable = false }
pytorch3d = { path = "./external/pytorch3d", editable = false }
nuscenes-devkit = { path = "./external/nuscenes-devkit", editable = false }
xformers = { path = "./external/xformers", editable = false }
